### ISSUE TITLE
Documentation: Is this only GCE specific?

### ISSUE THREAD

**Issue by rjain-pivotal** [SAP/bosh-kubernetes-cpi-release#6]
Will this perform bare metal provisioning and how does this work with Ironic or any other bare metal provisioning layer?

**Comment by loewenstein** [comment]
This is about a Bosh CPI to provision Bosh releases to Kubernetes, not install Kubernetes itself. You might want to have a look at https://github.com/cloudfoundry-incubator/kubo-release

If provisioning Bosh releases to K8S is of interest I would recommend to have a look at https://github.com/bosh-cpis/bosh-kubernetes-cpi-release
